-- Create a table for user data
create table if not exists user_data (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  data_key text not null,
  data_value jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, data_key)
);

-- Enable RLS
alter table user_data enable row level security;

-- Create policies
create policy "Users can view their own data" on user_data
  for select using (auth.uid() = user_id);

create policy "Users can insert their own data" on user_data
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own data" on user_data
  for update using (auth.uid() = user_id);
